export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SNAPSHOT_READONLY: "SNAPSHOT_READONLY",
  PHASE_NOT_SUBMITTED: "PHASE_NOT_SUBMITTED",
  CLAUSE_NOT_HIGH_RISK: "CLAUSE_NOT_HIGH_RISK",
  ROLE_ALREADY_SIGNED: "ROLE_ALREADY_SIGNED",
  SIGNER_CONFLICT: "SIGNER_CONFLICT",
  SIGNER_NAME_REQUIRED: "SIGNER_NAME_REQUIRED",
  DRAFT_NOT_FOUND: "DRAFT_NOT_FOUND",
  VERSION_COMPLETED: "VERSION_COMPLETED"
} as const;
