export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SNAPSHOT_READONLY: "SNAPSHOT_READONLY",
  SIGNER_ROLE_CONFLICT: "SIGNER_ROLE_CONFLICT",
  ROLE_ALREADY_SIGNED: "ROLE_ALREADY_SIGNED",
  NON_HIGH_RISK_NO_SIGNATURE: "NON_HIGH_RISK_NO_SIGNATURE",
  HISTORICAL_SNAPSHOT_LOCKED: "HISTORICAL_SNAPSHOT_LOCKED"
} as const;
